#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPOM
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TrackingVaccine_05")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertakun(akun instance);
    partial void Updateakun(akun instance);
    partial void Deleteakun(akun instance);
    partial void Insertrole(role instance);
    partial void Updaterole(role instance);
    partial void Deleterole(role instance);
    partial void Insertakun_pasien(akun_pasien instance);
    partial void Updateakun_pasien(akun_pasien instance);
    partial void Deleteakun_pasien(akun_pasien instance);
    partial void Insertdaftar_vaksin(daftar_vaksin instance);
    partial void Updatedaftar_vaksin(daftar_vaksin instance);
    partial void Deletedaftar_vaksin(daftar_vaksin instance);
    partial void Insertpembelian_vaksin(pembelian_vaksin instance);
    partial void Updatepembelian_vaksin(pembelian_vaksin instance);
    partial void Deletepembelian_vaksin(pembelian_vaksin instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["TrackingVaccine_05ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<akun> akuns
		{
			get
			{
				return this.GetTable<akun>();
			}
		}
		
		public System.Data.Linq.Table<role> roles
		{
			get
			{
				return this.GetTable<role>();
			}
		}
		
		public System.Data.Linq.Table<akun_pasien> akun_pasiens
		{
			get
			{
				return this.GetTable<akun_pasien>();
			}
		}
		
		public System.Data.Linq.Table<daftar_vaksin> daftar_vaksins
		{
			get
			{
				return this.GetTable<daftar_vaksin>();
			}
		}
		
		public System.Data.Linq.Table<pembelian_vaksin> pembelian_vaksins
		{
			get
			{
				return this.GetTable<pembelian_vaksin>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.akun")]
	public partial class akun : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_akun;
		
		private string _username;
		
		private string _PASSWORD;
		
		private int _role;
		
		private EntitySet<pembelian_vaksin> _pembelian_vaksins;
		
		private EntityRef<role> _role1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_akunChanging(int value);
    partial void Onid_akunChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnPASSWORDChanging(string value);
    partial void OnPASSWORDChanged();
    partial void OnroleChanging(int value);
    partial void OnroleChanged();
    #endregion
		
		public akun()
		{
			this._pembelian_vaksins = new EntitySet<pembelian_vaksin>(new Action<pembelian_vaksin>(this.attach_pembelian_vaksins), new Action<pembelian_vaksin>(this.detach_pembelian_vaksins));
			this._role1 = default(EntityRef<role>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_akun", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_akun
		{
			get
			{
				return this._id_akun;
			}
			set
			{
				if ((this._id_akun != value))
				{
					this.Onid_akunChanging(value);
					this.SendPropertyChanging();
					this._id_akun = value;
					this.SendPropertyChanged("id_akun");
					this.Onid_akunChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSWORD", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string PASSWORD
		{
			get
			{
				return this._PASSWORD;
			}
			set
			{
				if ((this._PASSWORD != value))
				{
					this.OnPASSWORDChanging(value);
					this.SendPropertyChanging();
					this._PASSWORD = value;
					this.SendPropertyChanged("PASSWORD");
					this.OnPASSWORDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_role", DbType="Int NOT NULL")]
		public int role
		{
			get
			{
				return this._role;
			}
			set
			{
				if ((this._role != value))
				{
					if (this._role1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnroleChanging(value);
					this.SendPropertyChanging();
					this._role = value;
					this.SendPropertyChanged("role");
					this.OnroleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="akun_pembelian_vaksin", Storage="_pembelian_vaksins", ThisKey="id_akun", OtherKey="id_akun")]
		public EntitySet<pembelian_vaksin> pembelian_vaksins
		{
			get
			{
				return this._pembelian_vaksins;
			}
			set
			{
				this._pembelian_vaksins.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="role_akun", Storage="_role1", ThisKey="role", OtherKey="id_role", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public role role1
		{
			get
			{
				return this._role1.Entity;
			}
			set
			{
				role previousValue = this._role1.Entity;
				if (((previousValue != value) 
							|| (this._role1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._role1.Entity = null;
						previousValue.akuns.Remove(this);
					}
					this._role1.Entity = value;
					if ((value != null))
					{
						value.akuns.Add(this);
						this._role = value.id_role;
					}
					else
					{
						this._role = default(int);
					}
					this.SendPropertyChanged("role1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_pembelian_vaksins(pembelian_vaksin entity)
		{
			this.SendPropertyChanging();
			entity.akun = this;
		}
		
		private void detach_pembelian_vaksins(pembelian_vaksin entity)
		{
			this.SendPropertyChanging();
			entity.akun = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.role")]
	public partial class role : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_role;
		
		private string _nama_role;
		
		private EntitySet<akun> _akuns;
		
		private EntitySet<akun_pasien> _akun_pasiens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_roleChanging(int value);
    partial void Onid_roleChanged();
    partial void Onnama_roleChanging(string value);
    partial void Onnama_roleChanged();
    #endregion
		
		public role()
		{
			this._akuns = new EntitySet<akun>(new Action<akun>(this.attach_akuns), new Action<akun>(this.detach_akuns));
			this._akun_pasiens = new EntitySet<akun_pasien>(new Action<akun_pasien>(this.attach_akun_pasiens), new Action<akun_pasien>(this.detach_akun_pasiens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_role", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_role
		{
			get
			{
				return this._id_role;
			}
			set
			{
				if ((this._id_role != value))
				{
					this.Onid_roleChanging(value);
					this.SendPropertyChanging();
					this._id_role = value;
					this.SendPropertyChanged("id_role");
					this.Onid_roleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama_role", DbType="VarChar(10)")]
		public string nama_role
		{
			get
			{
				return this._nama_role;
			}
			set
			{
				if ((this._nama_role != value))
				{
					this.Onnama_roleChanging(value);
					this.SendPropertyChanging();
					this._nama_role = value;
					this.SendPropertyChanged("nama_role");
					this.Onnama_roleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="role_akun", Storage="_akuns", ThisKey="id_role", OtherKey="role")]
		public EntitySet<akun> akuns
		{
			get
			{
				return this._akuns;
			}
			set
			{
				this._akuns.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="role_akun_pasien", Storage="_akun_pasiens", ThisKey="id_role", OtherKey="role")]
		public EntitySet<akun_pasien> akun_pasiens
		{
			get
			{
				return this._akun_pasiens;
			}
			set
			{
				this._akun_pasiens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_akuns(akun entity)
		{
			this.SendPropertyChanging();
			entity.role1 = this;
		}
		
		private void detach_akuns(akun entity)
		{
			this.SendPropertyChanging();
			entity.role1 = null;
		}
		
		private void attach_akun_pasiens(akun_pasien entity)
		{
			this.SendPropertyChanging();
			entity.role1 = this;
		}
		
		private void detach_akun_pasiens(akun_pasien entity)
		{
			this.SendPropertyChanging();
			entity.role1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.akun_pasien")]
	public partial class akun_pasien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_akun;
		
		private string _nama;
		
		private string _nik;
		
		private string _username;
		
		private string _password;
		
		private int _role;
		
		private EntityRef<role> _role1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_akunChanging(int value);
    partial void Onid_akunChanged();
    partial void OnnamaChanging(string value);
    partial void OnnamaChanged();
    partial void OnnikChanging(string value);
    partial void OnnikChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnroleChanging(int value);
    partial void OnroleChanged();
    #endregion
		
		public akun_pasien()
		{
			this._role1 = default(EntityRef<role>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_akun", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_akun
		{
			get
			{
				return this._id_akun;
			}
			set
			{
				if ((this._id_akun != value))
				{
					this.Onid_akunChanging(value);
					this.SendPropertyChanging();
					this._id_akun = value;
					this.SendPropertyChanged("id_akun");
					this.Onid_akunChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string nama
		{
			get
			{
				return this._nama;
			}
			set
			{
				if ((this._nama != value))
				{
					this.OnnamaChanging(value);
					this.SendPropertyChanging();
					this._nama = value;
					this.SendPropertyChanged("nama");
					this.OnnamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nik", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string nik
		{
			get
			{
				return this._nik;
			}
			set
			{
				if ((this._nik != value))
				{
					this.OnnikChanging(value);
					this.SendPropertyChanging();
					this._nik = value;
					this.SendPropertyChanged("nik");
					this.OnnikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_role", DbType="Int NOT NULL")]
		public int role
		{
			get
			{
				return this._role;
			}
			set
			{
				if ((this._role != value))
				{
					if (this._role1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnroleChanging(value);
					this.SendPropertyChanging();
					this._role = value;
					this.SendPropertyChanged("role");
					this.OnroleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="role_akun_pasien", Storage="_role1", ThisKey="role", OtherKey="id_role", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public role role1
		{
			get
			{
				return this._role1.Entity;
			}
			set
			{
				role previousValue = this._role1.Entity;
				if (((previousValue != value) 
							|| (this._role1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._role1.Entity = null;
						previousValue.akun_pasiens.Remove(this);
					}
					this._role1.Entity = value;
					if ((value != null))
					{
						value.akun_pasiens.Add(this);
						this._role = value.id_role;
					}
					else
					{
						this._role = default(int);
					}
					this.SendPropertyChanged("role1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.daftar_vaksin")]
	public partial class daftar_vaksin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_vaksin;
		
		private string _id_registrasi;
		
		private string _nama_vaksin;
		
		private string _jenis_vaksin;
		
		private string _jumlah;
		
		private string _status_vaksin;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_vaksinChanging(int value);
    partial void Onid_vaksinChanged();
    partial void Onid_registrasiChanging(string value);
    partial void Onid_registrasiChanged();
    partial void Onnama_vaksinChanging(string value);
    partial void Onnama_vaksinChanged();
    partial void Onjenis_vaksinChanging(string value);
    partial void Onjenis_vaksinChanged();
    partial void OnjumlahChanging(string value);
    partial void OnjumlahChanged();
    partial void Onstatus_vaksinChanging(string value);
    partial void Onstatus_vaksinChanged();
    #endregion
		
		public daftar_vaksin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_vaksin", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_vaksin
		{
			get
			{
				return this._id_vaksin;
			}
			set
			{
				if ((this._id_vaksin != value))
				{
					this.Onid_vaksinChanging(value);
					this.SendPropertyChanging();
					this._id_vaksin = value;
					this.SendPropertyChanged("id_vaksin");
					this.Onid_vaksinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_registrasi", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string id_registrasi
		{
			get
			{
				return this._id_registrasi;
			}
			set
			{
				if ((this._id_registrasi != value))
				{
					this.Onid_registrasiChanging(value);
					this.SendPropertyChanging();
					this._id_registrasi = value;
					this.SendPropertyChanged("id_registrasi");
					this.Onid_registrasiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama_vaksin", DbType="VarChar(225) NOT NULL", CanBeNull=false)]
		public string nama_vaksin
		{
			get
			{
				return this._nama_vaksin;
			}
			set
			{
				if ((this._nama_vaksin != value))
				{
					this.Onnama_vaksinChanging(value);
					this.SendPropertyChanging();
					this._nama_vaksin = value;
					this.SendPropertyChanged("nama_vaksin");
					this.Onnama_vaksinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jenis_vaksin", DbType="VarChar(225) NOT NULL", CanBeNull=false)]
		public string jenis_vaksin
		{
			get
			{
				return this._jenis_vaksin;
			}
			set
			{
				if ((this._jenis_vaksin != value))
				{
					this.Onjenis_vaksinChanging(value);
					this.SendPropertyChanging();
					this._jenis_vaksin = value;
					this.SendPropertyChanged("jenis_vaksin");
					this.Onjenis_vaksinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jumlah", DbType="VarChar(225) NOT NULL", CanBeNull=false)]
		public string jumlah
		{
			get
			{
				return this._jumlah;
			}
			set
			{
				if ((this._jumlah != value))
				{
					this.OnjumlahChanging(value);
					this.SendPropertyChanging();
					this._jumlah = value;
					this.SendPropertyChanged("jumlah");
					this.OnjumlahChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status_vaksin", DbType="VarChar(255)")]
		public string status_vaksin
		{
			get
			{
				return this._status_vaksin;
			}
			set
			{
				if ((this._status_vaksin != value))
				{
					this.Onstatus_vaksinChanging(value);
					this.SendPropertyChanging();
					this._status_vaksin = value;
					this.SendPropertyChanged("status_vaksin");
					this.Onstatus_vaksinChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.pembelian_vaksin")]
	public partial class pembelian_vaksin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_pembelian;
		
		private System.Nullable<int> _id_akun;
		
		private string _nama;
		
		private string _jumlah;
		
		private string _alamat;
		
		private EntityRef<akun> _akun;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_pembelianChanging(int value);
    partial void Onid_pembelianChanged();
    partial void Onid_akunChanging(System.Nullable<int> value);
    partial void Onid_akunChanged();
    partial void OnnamaChanging(string value);
    partial void OnnamaChanged();
    partial void OnjumlahChanging(string value);
    partial void OnjumlahChanged();
    partial void OnalamatChanging(string value);
    partial void OnalamatChanged();
    #endregion
		
		public pembelian_vaksin()
		{
			this._akun = default(EntityRef<akun>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pembelian", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_pembelian
		{
			get
			{
				return this._id_pembelian;
			}
			set
			{
				if ((this._id_pembelian != value))
				{
					this.Onid_pembelianChanging(value);
					this.SendPropertyChanging();
					this._id_pembelian = value;
					this.SendPropertyChanged("id_pembelian");
					this.Onid_pembelianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_akun", DbType="Int")]
		public System.Nullable<int> id_akun
		{
			get
			{
				return this._id_akun;
			}
			set
			{
				if ((this._id_akun != value))
				{
					if (this._akun.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_akunChanging(value);
					this.SendPropertyChanging();
					this._id_akun = value;
					this.SendPropertyChanged("id_akun");
					this.Onid_akunChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama", DbType="VarChar(225) NOT NULL", CanBeNull=false)]
		public string nama
		{
			get
			{
				return this._nama;
			}
			set
			{
				if ((this._nama != value))
				{
					this.OnnamaChanging(value);
					this.SendPropertyChanging();
					this._nama = value;
					this.SendPropertyChanged("nama");
					this.OnnamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jumlah", DbType="VarChar(225) NOT NULL", CanBeNull=false)]
		public string jumlah
		{
			get
			{
				return this._jumlah;
			}
			set
			{
				if ((this._jumlah != value))
				{
					this.OnjumlahChanging(value);
					this.SendPropertyChanging();
					this._jumlah = value;
					this.SendPropertyChanged("jumlah");
					this.OnjumlahChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alamat", DbType="VarChar(255)")]
		public string alamat
		{
			get
			{
				return this._alamat;
			}
			set
			{
				if ((this._alamat != value))
				{
					this.OnalamatChanging(value);
					this.SendPropertyChanging();
					this._alamat = value;
					this.SendPropertyChanged("alamat");
					this.OnalamatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="akun_pembelian_vaksin", Storage="_akun", ThisKey="id_akun", OtherKey="id_akun", IsForeignKey=true, DeleteRule="CASCADE")]
		public akun akun
		{
			get
			{
				return this._akun.Entity;
			}
			set
			{
				akun previousValue = this._akun.Entity;
				if (((previousValue != value) 
							|| (this._akun.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._akun.Entity = null;
						previousValue.pembelian_vaksins.Remove(this);
					}
					this._akun.Entity = value;
					if ((value != null))
					{
						value.pembelian_vaksins.Add(this);
						this._id_akun = value.id_akun;
					}
					else
					{
						this._id_akun = default(Nullable<int>);
					}
					this.SendPropertyChanged("akun");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
