//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPOM.RumsakService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="pembelian_rumsak", Namespace="http://schemas.datacontract.org/2004/07/RumsakService")]
    [System.SerializableAttribute()]
    public partial class pembelian_rumsak : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_pembelian_rumsakField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string laporanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int vaksin_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_pembelian_rumsak {
            get {
                return this.id_pembelian_rumsakField;
            }
            set {
                if ((this.id_pembelian_rumsakField.Equals(value) != true)) {
                    this.id_pembelian_rumsakField = value;
                    this.RaisePropertyChanged("id_pembelian_rumsak");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string laporan {
            get {
                return this.laporanField;
            }
            set {
                if ((object.ReferenceEquals(this.laporanField, value) != true)) {
                    this.laporanField = value;
                    this.RaisePropertyChanged("laporan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int vaksin_id {
            get {
                return this.vaksin_idField;
            }
            set {
                if ((this.vaksin_idField.Equals(value) != true)) {
                    this.vaksin_idField = value;
                    this.RaisePropertyChanged("vaksin_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RumsakService.IRumsakService")]
    public interface IRumsakService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRumsakService/findAll", ReplyAction="http://tempuri.org/IRumsakService/findAllResponse")]
        BPOM.RumsakService.pembelian_rumsak[] findAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRumsakService/findAll", ReplyAction="http://tempuri.org/IRumsakService/findAllResponse")]
        System.Threading.Tasks.Task<BPOM.RumsakService.pembelian_rumsak[]> findAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRumsakService/findById", ReplyAction="http://tempuri.org/IRumsakService/findByIdResponse")]
        BPOM.RumsakService.pembelian_rumsak[] findById(int id_pembelian_rumsak);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRumsakService/findById", ReplyAction="http://tempuri.org/IRumsakService/findByIdResponse")]
        System.Threading.Tasks.Task<BPOM.RumsakService.pembelian_rumsak[]> findByIdAsync(int id_pembelian_rumsak);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRumsakService/AddLaporanRumsak", ReplyAction="http://tempuri.org/IRumsakService/AddLaporanRumsakResponse")]
        bool AddLaporanRumsak(BPOM.RumsakService.pembelian_rumsak dataPembelian);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRumsakService/AddLaporanRumsak", ReplyAction="http://tempuri.org/IRumsakService/AddLaporanRumsakResponse")]
        System.Threading.Tasks.Task<bool> AddLaporanRumsakAsync(BPOM.RumsakService.pembelian_rumsak dataPembelian);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRumsakServiceChannel : BPOM.RumsakService.IRumsakService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RumsakServiceClient : System.ServiceModel.ClientBase<BPOM.RumsakService.IRumsakService>, BPOM.RumsakService.IRumsakService {
        
        public RumsakServiceClient() {
        }
        
        public RumsakServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RumsakServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RumsakServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RumsakServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BPOM.RumsakService.pembelian_rumsak[] findAll() {
            return base.Channel.findAll();
        }
        
        public System.Threading.Tasks.Task<BPOM.RumsakService.pembelian_rumsak[]> findAllAsync() {
            return base.Channel.findAllAsync();
        }
        
        public BPOM.RumsakService.pembelian_rumsak[] findById(int id_pembelian_rumsak) {
            return base.Channel.findById(id_pembelian_rumsak);
        }
        
        public System.Threading.Tasks.Task<BPOM.RumsakService.pembelian_rumsak[]> findByIdAsync(int id_pembelian_rumsak) {
            return base.Channel.findByIdAsync(id_pembelian_rumsak);
        }
        
        public bool AddLaporanRumsak(BPOM.RumsakService.pembelian_rumsak dataPembelian) {
            return base.Channel.AddLaporanRumsak(dataPembelian);
        }
        
        public System.Threading.Tasks.Task<bool> AddLaporanRumsakAsync(BPOM.RumsakService.pembelian_rumsak dataPembelian) {
            return base.Channel.AddLaporanRumsakAsync(dataPembelian);
        }
    }
}
