//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VaccineService
{
    using System;
    using System.Collections.Generic;
    
    public partial class daftar_vaksin
    {
        public int id_vaksin { get; set; }
        public string id_registrasi { get; set; }
        public string nama_vaksin { get; set; }
        public string jenis_vaksin { get; set; }
        public string jumlah { get; set; }
        public string status_vaksin { get; set; }
    }
}
