//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RumsakService
{
    using System;
    using System.Collections.Generic;
    
    public partial class pembelian_rumsak
    {
        public int id_pembelian_rumsak { get; set; }
        public int vaksin_id { get; set; }
        public string laporan { get; set; }
    }
}
